baseurl = "/"
languageCode = "en-us"
theme = "devfest-theme-hugo"

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

[params]
    title = "DeliveryConf 2020"
    date = "2020-01-21"
    description = "DeliveryConf is an awesome continuous delivery conference"
    images = ["/images/social-share.jpg"]
    email = "info@deliveryconf.com"
    keywords = "continuous delivery, continuous integration, cloud, testing, dev"
    copyright = "&copy; 2019 DeliveryConf"
    cfpUrl = "https://conference-hall.io/public/event/HJRThubF4uYPkb7jSUxi"
    subscriptionUrl = "http://eepurl.com/dps1j5"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"

[params.logos]
    jumbo = "/images/logos/awesome-logo.png"
    header = "/images/logos/awesome-logo.png"
    footer = "/images/logos/awesome-logo.png"

[menu]
[[menu.main]]
    identifier = "schedule"
    name = "Schedule"
    url = "https://deliveryconf.busyconf.com/schedule"
    weight = 200
    external = true

[languages]
[languages.en]
    weight = 1
    languageName = "gb"

[taxonomies]
  tag = "tags"